######################################################################
#
# File name : SPI_Wrapper_compile.do
# Created on: Tue Jun 19 09:45:35 +0200 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../LC3_Projekt.srcs/sources_1/new/d_ff.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/shift_universal.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/counter.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/SPI.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/mod_m_counter.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/slow_clk.vhd" \
"../../../../LC3_Projekt.srcs/sources_1/new/SPI_Wrapper.vhd" \


quit -force

